project/about/urls.py
from django.urls import path
from . import views

app_name = "about" 
urlpatterns =[
    path('', views.index, name="index"),
    path('ER/', views.ER, name="ER"),
    path('Goals/', views.Goals, name="Goals"),
    path('Personas/', views.Personas, name="Personas"),
    path('stories/', views.stories, name="stories"),
    path('Sitemap/', views.Sitemap, name="Sitemap"),
    path('Descriptions/', views.Descriptions, name="Descriptions"),
    path('Wireframes/', views.Wireframes, name="Wireframes"),
    path('non_funtional/', views.non_funtional, name="non_funtional"),

]

project/accounts/urls.py
from django.urls import path


from .views import SignUpView,PasswordChangeView , CustomUserChangeView 
from . import views

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(),name='EditPassword'  ),
    path('editProfile/',CustomUserChangeView.as_view(),name='EditProfile' ),
]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls')),
    path('recipe/', include('recipe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/recipe/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "recipe" 
urlpatterns =[
    path('', views.index_recipe, name="index"),
    path('meat', views.meat, name="meat"),
    path('norm', views.dessert, name="norm"),
    path('hal', views.halal, name="hal"),
    path('bev', views.beverag, name="bev"),
    path('oco', views.ovovegen, name="oco"),
    path('vegy', views.vegy, name="vegy"),
    path('app', views.appetizer, name="app"),
    path('<int:menu_id>',views.menu,name="menu"),
    path('<int:menu_id>/comment/',AddCommentView.as_view(),name="AddComment") ,
    path('addrecipe',AddRecipe.as_view(),name="addrecipe"),
    path('complete',views.complete,name="complete"),
    path('<int:menu_id>/like',views.like,name="like"),
    path('send/', SendPetition.as_view(), name='send'),
    path('<int:menu_id>/confirm/',SendConfirm.as_view(), name='confirm'),
    path('search', Search.as_view(), name="search"),
    path('result', views.result, name="result"),
    path('myrecipe', views.myrecipe , name="myrecipe"),
    path('mylike', views.mylike, name="mylike"),
    path('purchased', views.purchased, name="purchased"),
    path('order', views.admin_order, name="order"),
    path('<int:o_id>/check',views.confirm_slip,name="check"),
    path('useraddmenu', views.admin_addmenu, name="addmenu"),
    path('petition', views.admin_petition, name="petition"),



]

project/accounts/models.py
from django.db import models

# Create your models here.
# class petition (models.Model):
#     user=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
#     petition = models.TextField(blank=True)
#     date_added =models.DateTimeField(auto_now_add=True)
#     class status(models.TextChoices):
#         no = "no"
#         confirm = "confirm"
#     confirm = models.CharField(max_length=10,
#         choices=status.choices,
#         default=status.confirm.no,
#         )
#     def __str__(self) -> str:
#         return f"{self.user,self.date}"

project/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    
    first_name = forms.CharField(label = "First name",)
    last_name = forms.CharField(label = "Last name")
    
    class Meta:
        model = User
        fields = ('username', 'email' ,'first_name','last_name')
  
class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('username','email' ,'first_name','last_name')

project/accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from .forms import *
from django.http import HttpResponseRedirect
from django.contrib.auth.views import *
from django.contrib.auth.forms import *
from django.shortcuts import render ,get_object_or_404
from django.urls import reverse


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

class PasswordChangeView(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy('home')
    template_name = 'registration/editpassword.html'

class CustomUserChangeView(UpdateView):
    form_class = CustomUserChangeForm
    success_url = reverse_lazy('home')
    template_name = 'registration/editProfile.html'
    def get_object(self):
        return self.request.user

project/accounts/templates/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="with=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- <link rel="stylesheet" href="{%static 'css/style-navbar.css'%}"> -->
  <meta charset="utf-8">
  <link rel="stylesheet" href="{%static 'css/home.css' %}">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

project/accounts/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}

{% if user.is_authenticated %}
<section class="header">
  <nav>
    <a href="{% url 'home' %}">
      {% load static %}
      <img src="{% static 'images/logo_2.png' %}" width="10%" /></a>
   
<div class="nav-links" id="navLinks">
  <i class="fa fa-times-circle-o" onclick="hideMenu()"></i>
  <ul>
    
    <li><a href="{% url 'home' %}">Home</a></li>
    <li><a href="{% url 'recipe:search' %}">Search</a></li>
    <li><a href="{% url 'recipe:index' %}">Category</a>
      <div class="sub-about">
        
        <ul>
          <li><a href = "{% url 'recipe:meat' %}" >Meat</a></li>
          <li><a href = "{% url 'recipe:app' %}" >Appitizer</a></li>
          <li><a href = "{% url 'recipe:bev' %}" >Beverage</a></li>
          <li><a href = "{% url 'recipe:hal' %}" >Halal</a></li>
          <li><a href = "{% url 'recipe:norm' %}" >Dessert</a></li>
          <li><a href = "{% url 'recipe:oco' %}" >Ovo vegan</a></li>
          <li><a href = "{% url 'recipe:vegy' %}" >Vegetarian</a></li></li>
      </ul>
    </div>
    </li>
    <li><a href="#" class="About">About</a>
      <div class="sub-about">
          <ul>
              <li><a href="{% url 'about:index' %}">Contact us</a></li>
              <li><a href="https://github.com/6210612773/cookbookfoodguide">Git Hub</a></li>
              <li><a href="https://www.pivotaltracker.com/n/projects/2535892">pivotaltracker</a></li>
          </ul>
      </div>
    </li>
    <li ><a href="{% url 'logout' %}">Log Out</a></li>
    <li ><a href="#">{{ user.username }}</a>
      <div class="sub-about">
        <ul>
          <li><a href = "{% url 'EditProfile' %}" >Edit profile</a></li>
          <li><a href = "{% url 'EditPassword' %}" >Edit password</a></li>
          
      </ul>
    </div>
    </li>
</ul></div>
<i class="fa fa-bars" onclick="showMenu()"></i>
</nav>

</section>
<!-- <div class="text-box">
  <h1>Welcome, {{ user.username }}!</h1>
  <p>
    You can reach out to us if you need any help or question 
  </p>
</div> -->
<div class="text-home">
  <h1>Welcome, {{ user.username }}!</h1>
  <p>
    You can reach out to us if you need any help or question <br><br>
  </p>
    <!-- {{ user.email }}</h1> -->
    {%if user.username == "admin" %}
    <a href = "{% url 'recipe:order' %}" >Order</a>
    <a class="btn" href = "{% url 'recipe:petition' %}">Petition</a>
    <a href = "{% url 'recipe:addmenu' %}" style="margin-left: 30px;">User add menu</a>
    <a class="btn" href = "{% url 'admin:index' %}" >Edit data</a>
  <!-- <button class="w3-button w3-round-xlarge" ><a href="{% url 'admin:index' %}">Edit data</a></button> -->
    {% else %}
    <a href = "{% url 'recipe:myrecipe' %}" >Your recipe</a>
    <a class="btn" href = "{% url 'recipe:mylike' %}" >Your favorite</a>
    <a href = "{% url 'recipe:purchased' %}" style="margin-left: 30px;" >Purchased</a>
    <a class="btn" href = "{% url 'recipe:addrecipe' %}" >Add recipe</a>
    <a href = "{% url 'recipe:petition' %}" style="margin-left: 30px;" >Purchased</a>
    {% endif %}
  </div>
{% else %}
<body>
  <section class="header">
    <nav>
      <a href="{% url 'home' %}">
        {% load static %}
        <img src="{% static 'images/logo_2.png' %}" width="10%" /></a>
     
  <div class="nav-links" id="navLinks">
    <i class="fa fa-times-circle-o" onclick="hideMenu()"></i>
    <ul>
      
      <li><a href="{% url 'home' %}">Home</a></li>
      <li><a href="{% url 'recipe:search' %}">Search</a></li>
      <li><a href="{% url 'recipe:index' %}">Category</a>
        <div class="sub-about">
          <ul>
            <li><a href = "{% url 'recipe:meat' %}" >Meat</a></li>
            <li><a href = "{% url 'recipe:app' %}" >Appitizer</a></li>
            <li><a href = "{% url 'recipe:bev' %}" >Beverage</a></li>
            <li><a href = "{% url 'recipe:hal' %}" >Halal</a></li>
            <li><a href = "{% url 'recipe:norm' %}" >Dessert</a></li>
            <li><a href = "{% url 'recipe:oco' %}" >Oco vegan</a></li>
            <li><a href = "{% url 'recipe:vegy' %}" >Vegetarian</a></li></li>
        </ul>
      </div>
      </li>
      <li><a href="#" class="About">About</a>
       <div class="sub-about">
            <ul>
                <li><a href="{% url 'about:index' %}">Contact us</a></li>
                <li><a href="https://github.com/6210612773/cookbookfoodguide">Git Hub</a></li>
                <li><a href="https://www.pivotaltracker.com/n/projects/2535892">pivotaltracker</a></li>
            </ul>
        </div>
      </li>
      <li ><a href="{% url 'login' %}">Log In</a></li>
      <li ><a href="{% url 'signup' %}">Sign Up</a></li>
</ul></div>
<i class="fa fa-bars" onclick="showMenu()"></i>
</nav>
  <div class="text-box">
    <h1> Cookbook Foodguide</h1>
    <p> Please select your ingredient and enjoy your recipe</p>
    <a href="{% url 'recipe:search' %}" class="hero-btn">Search</a>
  </div>
</section>

<script>

    var navLinks = document.getElementById("navLinks");

    function showMenu(){
      navLinks.style.right = "0";
    }
    function hideMenu(){
      navLinks.style.right = "-200px";
    }

</script>



  </body>
{% endif %}
{% endblock %}