project/about/urls.py
from django.urls import path
from . import views

app_name = "about" 
urlpatterns =[
    path('', views.index, name="index"),
    path('ER/', views.ER, name="ER"),
    path('Goals/', views.Goals, name="Goals"),
    path('Personas/', views.Personas, name="Personas"),
    path('stories/', views.stories, name="stories"),
    path('Sitemap/', views.Sitemap, name="Sitemap"),
    path('Descriptions/', views.Descriptions, name="Descriptions"),
    path('Wireframes/', views.Wireframes, name="Wireframes"),
    path('non_funtional/', views.non_funtional, name="non_funtional"),

]

project/project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls')),
    path('recipe/', include('recipe.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/recipe/urls.py
from django.urls import path

from . import views
from .views import *

app_name = "recipe" 
urlpatterns =[
    path('', views.index_recipe, name="index"),
    path('meat', views.meat, name="meat"),
    path('norm', views.dessert, name="norm"),
    path('hal', views.halal, name="hal"),
    path('bev', views.beverag, name="bev"),
    path('oco', views.ovovegen, name="oco"),
    path('vegy', views.vegy, name="vegy"),
    path('app', views.appetizer, name="app"),
    path('<int:menu_id>',views.menu,name="menu"),
    path('<int:menu_id>/comment/',AddCommentView.as_view(),name="AddComment") ,
    path('addrecipe',AddRecipe.as_view(),name="addrecipe"),
    path('complete',views.complete,name="complete"),
    path('<int:menu_id>/like',views.like,name="like"),
    path('send/', SendPetition.as_view(), name='send'),
    path('<int:menu_id>/confirm/',SendConfirm.as_view(), name='confirm'),
    path('search', Search.as_view(), name="search"),
    path('result', views.result, name="result"),
    path('myrecipe', views.myrecipe , name="myrecipe"),
    path('mylike', views.mylike, name="mylike"),
    path('purchased', views.purchased, name="purchased"),
    path('order', views.admin_order, name="order"),
    path('<int:o_id>/check',views.confirm_slip,name="check"),
    path('useraddmenu', views.admin_addmenu, name="addmenu"),
    path('petition', views.admin_petition, name="petition"),



]

project/recipe/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class ingredient(models.Model):
    class material(models.TextChoices):
        meat = "meat"
        carbohydrate = "carbohydrate"
        vegetable = "vegetable"
        condiment = "condiment"
        fruit = "fruit"
        other = "other"
    ingredient = models.CharField(max_length=100,default=None)
    type = models.CharField(max_length=100,
        choices=material.choices,
        default=material.other,
        )

    def __str__(self) -> str:
        return f"{self.ingredient}"

class recipe(models.Model):

    class mode(models.TextChoices):
        dessert = "dessert"
        meat = "meat"
        halal = "halal"
        beverag = "beverag"
        ovovegen = "ovovegen"
        vegy = "vegetarian"
        appetizer = "appetizer"


    pic = models.ImageField(upload_to="",blank=True,null=True)
    menu = models.CharField(max_length=100,default=None)
    ingredient_unit = models.TextField(blank=True)
    HowToDo = models.TextField(blank=True)
    ingredientInmenu =models.ManyToManyField(ingredient,blank=True,related_name="ingredientInrecipe")
    type = models.CharField(max_length=100,
        choices=mode.choices,
        default=None,
        )
    
    status = ''
    
    price = models.FloatField(default=None, null=True)
    calorie = models.IntegerField(default=None, null=True)
    member = models.ManyToManyField(User,blank=True,related_name="member")
    like = models.ManyToManyField(User,blank=True,related_name="like")


    def __str__(self) -> str:
        return f"{self.menu}"

class Comment(models.Model):
    post = models.ForeignKey(recipe,on_delete=models.CASCADE,related_name="comments")
    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
    body = models.TextField(default=None)
    date_added =models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f"{self.post}"

class Addrecipe(models.Model):
    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
    bankaccount = models.CharField(default=None,max_length=20)

    class status(models.TextChoices):
        no = "no"
        confirm = "confirm"

    class mode(models.TextChoices):
        dessert = "dessert"
        meat = "meat"
        halal = "halal"
        beverag = "beverag"
        ovovegen = "ovovegen"
        vegy = "vegetarian"
        appetizer = "appetizer"

    pic = models.ImageField(upload_to="")
    menu = models.CharField(max_length=100,default=None)
    ingredient_unit = models.TextField(blank=True)
    HowToDo = models.TextField(blank=True)
    

    type = models.CharField(max_length=100,
        choices=mode.choices,
        default=None,
        )

    confirm = models.CharField(max_length=10,
        choices=status.choices,
        default=status.no,
        )

    price = models.IntegerField(default=None, null=True)
    calorie = models.IntegerField(default=None, null=True)
    
    def __str__(self) -> str:
        return f"{self.menu}"

class order (models.Model):
    class status(models.TextChoices):
        no = "no"
        confirm = "confirm"
    
    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT,related_name="userbuy")
    order = models.ForeignKey(recipe,on_delete=models.CASCADE,default=None,related_name="menu_order")
    price = models.FloatField(default=None, null=True)
    pic = models.ImageField(upload_to="")
    date = models.DateField(editable=True)
    time = models.TimeField(editable=True,default=None)
    name = models.CharField(max_length=100,default=None)
    bankaccount = models.CharField(default=None,max_length=4)
    confirm = models.CharField(max_length=10,
        choices=status.choices,
        default=status.no,
        )
    def __str__(self) -> str:
        return f"{self.name,self.time}"

class search (models.Model):
    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT,related_name="usersearch")
    Have = models.ManyToManyField(ingredient,blank=True,related_name="Have")
    DontNeed =models.ManyToManyField(ingredient,blank=True,related_name="dontNeed")

    def __str__(self) -> str:
        return f"{self.user}"

class petition (models.Model):
    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
    petition = models.TextField(blank=True)
    date_added =models.DateTimeField(auto_now_add=True)
    class status(models.TextChoices):
        no = "no"
        confirm = "confirm"
    confirm = models.CharField(max_length=10,
        choices=status.choices,
        default=status.no,
        )
    def __str__(self) -> str:
        return f"{self.user,self.date_added}"

project/recipe/forms.py
from django.forms import widgets
from django.http import request




from .models import Comment, recipe , Addrecipe ,petition,order,search
from django import forms


class CommentForm(forms.ModelForm):

    class Meta:
       model = Comment
       fields = ('body',)

       widgets = {'body': forms.Textarea}
       

class AddForm(forms.ModelForm):
    class Meta:
       model = Addrecipe
       fields = ('bankaccount','menu','pic','ingredient_unit',
       'HowToDo','type','price','calorie')

       widgets = {'bankaccount': forms.TextInput}

class SendPetition(forms.ModelForm):

    class Meta:
        model = petition
        fields = ('petition',)

class SendComfirm(forms.ModelForm):
    class Meta:
        model = order
        fields = ('pic','date','time','name','bankaccount',)
        widgets = {'date': forms.SelectDateWidget,
                    'time': forms.TimeInput(attrs={'type': 'time'},),
                    }
        

class Search(forms.ModelForm):

    class Meta:
        model = search
        fields = ('Have','DontNeed')
        widgets = {'Have': forms.CheckboxSelectMultiple,
                    'DontNeed' : forms.CheckboxSelectMultiple}






        
       

project/recipe/views.py
from django.forms.widgets import NullBooleanSelect
from django.shortcuts import render ,get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic.edit import CreateView
from .forms import *
from django.urls import reverse_lazy
from . import views
# Create your views here.

from django.contrib.auth.models import User

from .models import *

def index_recipe (request):
    return render(request,'recipe/index.html',{
        "recipes": recipe.objects.all(),
        })


def meat (request):
    return render(request,'recipe/meat.html',{
        "recipes": recipe.objects.all(),
        })


def dessert (request):
    return render(request,'recipe/dessert.html',{
        "recipes": recipe.objects.all(),
        })


def halal (request):
    return render(request,'recipe/halal.html',{
        "recipes": recipe.objects.all(),
        })


def beverag (request):
    return render(request,'recipe/beverag.html',{
        "recipes": recipe.objects.all(),
        })


def ovovegen (request):
    return render(request,'recipe/ovovegen.html',{
        "recipes": recipe.objects.all(),
        })


def vegy (request):
    return render(request,'recipe/vegy.html',{
        "recipes": recipe.objects.all(),
        })
    

def appetizer (request):
    return render(request,'recipe/appetizer.html',{
        "recipes": recipe.objects.all(),
        })


def complete (request):
    return render(request,'recipe/complete.html')


def menu (request,menu_id):
    Recipe = get_object_or_404(recipe,pk=menu_id)
    
    if  Recipe.price == None or Recipe.price == 0.0:
        Recipe.status = "free"
        Recipe.save()        
    else :
        Recipe.status = "price"
        Recipe.save()    
        if not request.user.is_authenticated:
            return HttpResponseRedirect(reverse("login"))
    howtodo=Recipe.HowToDo.split('>')
    ingredient=Recipe.ingredient_unit.split('>')

        

    return render(request,"recipe/menu.html",{
        "menu": Recipe,
        "comment": Comment.objects.all(), 
        'user':request.user, 
        'howtodo':howtodo , 
        'ingredient':ingredient
    })


def like (request,menu_id):
    Recipe = get_object_or_404(recipe,pk=menu_id)

    if request.user in Recipe.like.all():
        Recipe.like.remove(request.user)
    else:
        Recipe.like.add(request.user)
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))
    


def result (request):
    All = recipe.objects.all()
    if not request.user.is_authenticated:
        no_user = User.objects.get(username="nologin")
        find = search.objects.get(user_id=no_user)
    else:
        find = search.objects.get(user_id=request.user)
    
    menuHave = []
    menuDontNeed = []
    output=[]

    for menu in All:
        for ingInMenu in menu.ingredientInmenu.all():
            for ingHave in find.Have.all():
                if menu not in menuHave:
                    if ingHave == ingInMenu:
                        menuHave.append(menu)  
                        output.append(menu) 
            for ingNo in find.DontNeed.all():
                if ingNo == ingInMenu:
                        menuDontNeed.append(menu)
    
    for delectDontNeed in menuHave:
        for check in menuDontNeed:
            if  check == delectDontNeed:
                output.remove(delectDontNeed)

    if not output:
        output=[0]

    return render(request,'recipe/result.html',{
                "have":menuHave,
                "Dont":menuDontNeed,
                "all":All,
                "filter" :output
                }) 


def myrecipe (request):
    return render(request,'recipe/myrecipe.html',{
        "user":request.user,
        "MenuAddByUser": Addrecipe.objects.all(),
        })


def mylike (request):
    return render(request,'recipe/mylike.html',{
        "my":request.user,
        "recipes": recipe.objects.all(),
        })


def confirm_slip (request,o_id):
    all = recipe.objects.all()
    User_Order=order.objects.get(pk=o_id)
    User_Order.confirm = order.status.confirm
    User_Order.save()

    for menu in all:
        if User_Order.order == menu:
            menu.member.add(User_Order.user)
            menu.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'),)


def purchased (request):
    return render(request,'recipe/purchased.html',{
        "user":request.user,
        "recipes": recipe.objects.all(),
        })


def admin_order (request):
    return render(request,'recipe/admin_order.html',{
        "recipes": recipe.objects.all(),
        "order" : order.objects.all(),
        })


def admin_petition (request):
    return render(request,'recipe/admin_petition.html',{
        "petition" :petition.objects.all()
        })


def admin_addmenu (request):
    return render(request,'recipe/admin_addmenu.html',{
        "user_addmenu" :Addrecipe.objects.all()
        })


class SendPetition (CreateView):
    form_class = SendPetition
    success_url = reverse_lazy('home')
    template_name = 'recipe/add_petition.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class SendConfirm (CreateView):
    form_class = SendComfirm
    success_url = reverse_lazy('recipe:complete')
    template_name = 'recipe/add_confirm.html'

    def form_valid(self, form):
        form.instance.order_id = self.kwargs['menu_id']
        form.instance.user = self.request.user
        form.instance.price = (recipe.objects.get(id=self.kwargs['menu_id'])).price
        return super().form_valid(form)


class Search (CreateView):
    form_class = Search
    success_url = reverse_lazy('recipe:result')
    template_name = 'recipe/search.html'

    def form_valid(self, form):
        if not self.request.user.is_authenticated:
            search.objects.filter(user=User.objects.get(username="nologin")).delete()
            form.instance.user = User.objects.get(username="nologin")
        else:
            search.objects.filter(user=self.request.user).delete()
            form.instance.user = self.request.user

        return super().form_valid(form)


class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'recipe/add_comment.html'
    
    def form_valid(self, form):
        form.instance.post_id = self.kwargs['menu_id']
        self.x=self.kwargs['menu_id']
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):         
        return reverse_lazy('recipe:menu',args=[self.x])
    
    
class AddRecipe(CreateView):
    model = Addrecipe
    form_class = AddForm
    template_name = 'recipe/add_recipe.html'
    success_url = reverse_lazy('recipe:complete')

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.confirm = order.status.no
        return super().form_valid(form)
    

project/recipe/templates/Recipe/base_menu.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <meta charset="utf-8">
        <link rel="stylesheet" href="{%static 'css/style-cat.css'%}">
        <link rel="stylesheet" href="{%static 'css/menu.css'%}">
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <title>
            Category
        </title>
    </head>
    <body>
    <main>
        <section class="header">
            <nav>
              <a href="{% url 'home' %}">
                {% load static %}
                <img src="{% static 'images/logo_2.png' %}" width="10%" /></a>
            
          <div class="nav-links" id="navLinks">
            <i class="fa fa-times-circle-o" onclick="hideMenu()"></i>
            <ul>
              
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'recipe:search' %}">Search</a></li>
              <li><a href="{% url 'recipe:index' %}">Category</a>
                <div class="sub-about">
                  <ul>
                    <li><a href = "{% url 'recipe:meat' %}" >Meat</a></li>
                    <li><a href = "{% url 'recipe:app' %}" >Appitizer</a></li>
                    <li><a href = "{% url 'recipe:bev' %}" >Beverage</a></li>
                    <li><a href = "{% url 'recipe:hal' %}" >Halal</a></li>
                    <li><a href = "{% url 'recipe:norm' %}" >Dessert</a></li>
                    <li><a href = "{% url 'recipe:oco' %}" >Ovo vegan</a></li>
                    <li><a href = "{% url 'recipe:vegy' %}" >Vegetarian</a></li></li>
                </ul>
              </div>
              </li>
              <li><a href="#" class="About">About</a>
              <div class="sub-about">
                    <ul>
                        <li><a href="{% url 'about:index' %}">Contact us</a></li>
                        <li><a href="https://github.com/6210612773/cookbookfoodguide">Git Hub</a></li>
                        <li><a href="https://www.pivotaltracker.com/n/projects/2535892">pivotaltracker</a></li>
                    </ul>
                </div>
              </li>
              {% if user.is_authenticated %}
          <li ><a href="{% url 'logout' %}">Log Out</a></li>
          {% endif %}
              <li ><a href="#">{{ user.username }}</a>
		<div class="sub-about">
          <ul>
            <li><a href = "{% url 'EditProfile' %}" >Edit profile</a></li>
            <li><a href = "{% url 'EditPassword' %}" >Edit password</a></li>
            <li><a href = "{% url 'recipe:send' %}" >Contact us</a></li>
            
        </ul>
      </div>

	  </li>
          </ul></div>
          <i class="fa fa-bars" onclick="showMenu()"></i>
          </nav>
          
          </section>
        {% block content %}
        {% endblock %}
      </main>
    </body>
</html>

project/recipe/templates/Recipe/base_user.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="with=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" 
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w==" 
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="{%static 'css/addmenu.css' %}">
        <link rel="stylesheet" href="{%static 'css/style-navbar.css' %}">
        <title>
            Category
        </title>
    </head>
    <body>
    <main>
      {% if user.is_authenticated %}
      <section class="header">
        <nav>
          <a href="{% url 'home' %}">
            {% load static %}
            <img src="{% static 'images/logo_2.png' %}" width="10%" /></a>
         
      <div class="nav-links" id="navLinks">
        <i class="fa fa-times-circle-o" onclick="hideMenu()"></i>
        <ul>
          
          <li><a href="{% url 'home' %}">Home</a></li>
          <li><a href="{% url 'recipe:search' %}">Search</a></li>
          <li><a href="{% url 'recipe:index' %}">Category</a>
            <div class="sub-about">
              
              <ul>
                <li><a href = "{% url 'recipe:meat' %}" >Meat</a></li>
                <li><a href = "{% url 'recipe:app' %}" >Appitizer</a></li>
                <li><a href = "{% url 'recipe:bev' %}" >Beverage</a></li>
                <li><a href = "{% url 'recipe:hal' %}" >Halal</a></li>
                <li><a href = "{% url 'recipe:norm' %}" >Dessert</a></li>
                <li><a href = "{% url 'recipe:oco' %}" >Ovo vegan</a></li>
                <li><a href = "{% url 'recipe:vegy' %}" >Vegetarian</a></li></li>
            </ul>
          </div>
          </li>
          <li><a href="#" class="About">About</a>
            <div class="sub-about">
                <ul>
                    <li><a href="{% url 'about:index' %}">Contact us</a></li>
                    <li><a href="https://github.com/6210612773/cookbookfoodguide">Git Hub</a></li>
                    <li><a href="https://www.pivotaltracker.com/n/projects/2535892">pivotaltracker</a></li>
                </ul>
            </div>
          </li>
          <li ><a href="{% url 'logout' %}">Log Out</a></li>
          <li ><a href="#">{{ user.username }}</a>
            <div class="sub-about">
              <ul>
                <li><a href = "{% url 'EditProfile' %}" >Edit profile</a></li>
                <li><a href = "{% url 'EditPassword' %}" >Edit password</a></li>
                
            </ul>
          </div>
          </li>
      </ul></div>
      <i class="fa fa-bars" onclick="showMenu()"></i>
      </nav>
      
      </section>
      <!-- <div class="text-box">
        <h1>Welcome, {{ user.username }}!</h1>
        <p>
          You can reach out to us if you need any help or question 
        </p>
      </div> -->
   
      {% else %}
      <body>
        <section class="header">
          <nav>
            <a href="{% url 'home' %}">
              {% load static %}
              <img src="{% static 'images/logo_2.png' %}" width="10%" /></a>
           
        <div class="nav-links" id="navLinks">
          <i class="fa fa-times-circle-o" onclick="hideMenu()"></i>
          <ul>
            
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'recipe:search' %}">Search</a></li>
            <li><a href="#news">Category</a>
              <div class="sub-about">
                <ul>
                  <li><a href = "{% url 'recipe:meat' %}" >Meat</a></li>
                  <li><a href = "{% url 'recipe:app' %}" >Appitizer</a></li>
                  <li><a href = "{% url 'recipe:bev' %}" >Beverage</a></li>
                  <li><a href = "{% url 'recipe:hal' %}" >Halal</a></li>
                  <li><a href = "{% url 'recipe:norm' %}" >Normal</a></li>
                  <li><a href = "{% url 'recipe:oco' %}" >Oco vegan</a></li>
                  <li><a href = "{% url 'recipe:vegy' %}" >Vegetarian</a></li></li>
              </ul>
            </div>
            </li>
            <li><a href="#" class="About">About</a>
             <div class="sub-about">
                  <ul>
                      <li><a href="{% url 'about:index' %}">Contact us</a></li>
                      <li><a href="https://github.com/6210612773/cookbookfoodguide">Git Hub</a></li>
                      <li><a href="https://www.pivotaltracker.com/n/projects/2535892">pivotaltracker</a></li>
                  </ul>
              </div>
            </li>
            <li ><a href="{% url 'login' %}">Log In</a></li>
            <li ><a href="{% url 'signup' %}">Sign Up</a></li>
      </ul></div>
      <i class="fa fa-bars" onclick="showMenu()"></i>
      </nav>
       
      </section>
      
      <script>
      
          var navLinks = document.getElementById("navLinks");
      
          function showMenu(){
            navLinks.style.right = "0";
          }
          function hideMenu(){
            navLinks.style.right = "-200px";
          }
      
      </script>
      
      
      
        </body>
      {% endif %}
        {% block content %}

        {% endblock %}
      </main>
    </body>
</html>

project/recipe/templates/Recipe/index.html
{% extends 'recipe/layout.html' %}
{% load static %}
{% block content %}


<section class="dishes" id="dishes">
    <h1 class="heading">Recipe<span>Catagory</span></h1>
    <div class="box-container" style="margin-top: 3%; margin-bottom: 3%; margin-left: 3%; margin-right: 3%;">
        
        <div class="box">
            <a href = "{% url 'recipe:meat' %}" >
            <img class="image" src="{% static 'images/meat.jpg' %}" style="width: 50%; ;"/>
            </a>
            <center>Meat</center>
            </div>
        <div class="box">
            <a href = "{% url 'recipe:app' %}" >
            <img class="image" src="{% static 'images/apper.jpg' %}" style="width: 50%; ;"/>
            </a>
            <center>Appertizer</center>
            </div>
        <div class="box">
            <a href = "{% url 'recipe:bev' %}" >
            <img class="image" src="{% static 'images/bevv.jpg' %}" style="width: 50%; ;"/><br>
            </a>
            <center>Beverage</center>
            </div>
         <div class="box">
            <a href = "{% url 'recipe:hal' %}" >
            <img class="image" src="{% static 'images/halal.png' %}" style="width: 50%; ;"/><br>
            </a>
            <center>Halal</center>
            </div>
         <div class="box">
            <a href = "{% url 'recipe:norm' %}" >
            <img class="image" src="{% static 'images/dess.png' %}" style="width: 50%; ;"/><br>
            </a>
            <center>Dessert</center>
            </div>
         <div class="box">
            <a href = "{% url 'recipe:oco' %}" >
            <img class="image" src="{% static 'images/ocoveg.jpg' %}" style="width: 50%; ;"/><br>
            </a>
            <center>Ovo Vegeterian</center>
            </div>
        <div class="box">
            <a href = "{% url 'recipe:vegy' %}" >
            <img class="image" src="{% static 'images/veg.jpg' %}" style="width: 50%; ;"/><br>
            </a>
            <center>Vegeterian</center>
            </div>
        

    </div>
  </section>



    {% endblock %}

    

project/recipe/templates/Recipe/myRecipe.html
{% extends 'recipe/base_user.html' %}
{% load static %}
{% block content %}


<section class="dishes" id="dishes">
    <h1 class="heading">My<span>Recipe</span></h1>
    <div class="box-container" style="margin-top: 3%; margin-bottom: 3%; margin-left: 3%; margin-right: 3%;">
        {% for menu in MenuAddByUser %}
            {% if menu.user == user %}
            <div class="box">
                <img class="image" src="{{menu.pic.url}}" style="width: 50%; ;"/><br>
                <a href="{% url 'recipe:like' menu.id  %}" class="fa fa-heart"></a>
                <a href = "{% url 'recipe:menu' menu.id %}" >
                <h3>{{menu}}</h3></a>
            </div>
            {% endif %} 
        {% endfor %}    
    </div>
</section>

{% endblock %}

project/recipe/templates/Recipe/result.html
{% extends 'recipe/layout.html' %}

{% block title %}Add Recipe {% endblock %}

{% block content %}


<section class="dishes" id="dishes">
  <h1 class="heading">Result<span>Recipe</span></h1>
  <div class="box-container" style="margin-top: 3%; margin-bottom: 3%; margin-left: 3%; margin-right: 3%;">
    {% for menu in filter %} 
      {% if menu != 0 %}
        {% for list in all %}
          {% if menu == list %}
            <div class="box">
              <img class="image" src="{{list.pic.url}}" style="width: 50%; ;"/><br>
              <a href="{% url 'recipe:like' list.id  %}" class="fa fa-heart"></a>
              <a href = "{% url 'recipe:menu' list.id %}" >
              <h3>{{list.menu}}</h3></a>

              {% if list.price == None or list.price == 0.0 %}
                <span>free</span>
              {% else %} <br>
                <span>{{list.price}} $</span>
              {% endif %}
            </div>
          {% endif %}
        {% endfor %}
      {% else %} 
        <center>
          <br><br><br><br>
          <h1>don't have menu</h1><br><br><br>
          <p> Please select your ingredient and enjoy your recipe</p><br>
          <a href="{% url 'recipe:search' %}" class="hero-btn">Search</a>
        </center>
      {% endif %}
    {% endfor %}
  </div>
</section>

{% endblock %}